import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MonitorSmartphone, ShoppingCart } from 'lucide-react';
import Link from 'next/link';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    ads,
}: Readonly<{
    children: React.ReactNode;
    ads: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased
        bg-slate-800`}
            >
                <main className="w-full min-h-screen max-w-[1400px] mx-auto px-20 flex flex-col justify-between">
                    <header className="h-20 w-full flex justify-between">
                        <div className="flex items-center gap-2">
                            <MonitorSmartphone color="#ffffff" />
                            <Link href="/" className="text-white text-2xl">
                                Digital Shop
                            </Link>
                        </div>
                        <div className="flex items-center">
                            <ShoppingCart
                                strokeWidth="2.2"
                                size="25"
                                color="#ffffff"
                            />
                        </div>
                    </header>
                    <div className="mt-8 flex justify-center">{children}</div>
                    <div className="flex justify-center my-10">{ads}</div>{' '}
                    {/* slot */}
                    <footer className="flex justify-center items-center py-3 text-slate-300">
                        <p>&copy; 2025 All right reserved.</p>
                    </footer>
                </main>
            </body>
        </html>
    );
}
