import { currentUser } from '@clerk/nextjs/server';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await currentUser();
    const isAdmin = user?.privateMetadata?.isAdmin;
    if (!isAdmin) redirect('/');
    return <div className="w-full">{children}</div>;
}
